resource_types:
- name: irc-notification
  type: docker-image
  source:
    repository: flavorjones/irc-notification-resource

resources:
- name: docker-openscad.git
  type: git
  icon: github
  source:
    uri: https://github.com/openscad/docker-openscad.git
- name: every-monday-at-3-am-utc
  type: time
  source:
    start: "3:00"
    stop: "5:00"
    days: [Monday]
    location: UTC
- name: libera-openscad-ci
  type: irc-notification
  source:
    server: irc.libera.chat
    port: 6697
    join: true
    channel: ((openscad-ci-bot-channel))
    user: ((openscad-ci-bot-username))
    password: ((openscad-ci-bot-password))

- name: openscad-dev
  type: registry-image
  icon: docker
  source:
    repository: openscad/openscad
    tag: dev
    username: ((dockerhub-username))
    password: ((dockerhub-password))

jobs:
- name: build
  public: true
  plan:
  - put: libera-openscad-ci
    params:
      message: >
        Starting ${BUILD_TEAM_NAME}/${BUILD_PIPELINE_NAME}: build ${BUILD_ID} ${BUILD_URL}
  - get: every-monday-at-3-am-utc
    trigger: true
  - get: docker-openscad.git
  - task: generate-tag-name
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: debian
          tag: bookworm-slim
      outputs:
      - name: meta
      run:
        path: sh
        args:
          - -exc
          - date '+dev.%Y-%m-%d' > ./meta/tags
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          repository: concourse/oci-build-task
      inputs:
      - name: docker-openscad.git
      outputs:
      - name: image
      params:
        CONTEXT: ./docker-openscad.git/openscad/bookworm/
        DOCKERFILE: ./docker-openscad.git/openscad/bookworm/Dockerfile
      run:
        path: build
  - put: openscad-dev
    params:
      additional_tags: ./meta/tags
      image: ./image/image.tar
  on_success:
    put: libera-openscad-ci
    params:
      message: >
        Build successful ${BUILD_TEAM_NAME}/${BUILD_PIPELINE_NAME}: build ${BUILD_ID} ${BUILD_URL}
  on_failure:
    put: libera-openscad-ci
    params:
      message: >
        Build failed ${BUILD_TEAM_NAME}/${BUILD_PIPELINE_NAME}: build ${BUILD_ID} ${BUILD_URL}
